services:
  otterwiki:
    image: redimp/otterwiki:2
    restart: unless-stopped
    volumes:
      - ./app-data:/app-data
    networks:
      - proxy
    labels:
      - "traefik.enable=true"

      # Router HTTP
      - "traefik.http.routers.wiki.rule=Host(`wiki.morincharleseric.online`)"
      # - "traefik.http.routers.wiki.entrypoints=web"

      # Service + loadbalancer
      - "traefik.http.services.wiki.loadbalancer.server.port=8080"
      # Router HTTPS
      - "traefik.http.routers.wiki.entrypoints=websecure"
      - "traefik.http.routers.wiki.tls=true"
      - "traefik.http.routers.wiki.tls.certresolver=letsencrypt"

networks:
  proxy:
    external: true
