services:
  database:
    image: bubu11e/mariadb:v1.0
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    restart: unless-stopped
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - proxy

  backend:
    image: bubu11e/backend-express:v1.0 
    container_name: conteneur_backend
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.conteneur_backend.rule=Host(`tasklist.morincharleseric.online`) && PathPrefix(`/api/tasks`)"
      - "traefik.http.routers.conteneur_backend.entrypoints=websecure"
      - "traefik.http.routers.conteneur_backend.tls=true"
      - "traefik.http.routers.conteneur_backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.conteneur_backend.loadbalancer.server.port=3000"


  frontend:
    image: bubu11e/frontend-react:v2.1 
    container_name: conteneur_frontend
    # ports:
    #   - "8080:8080"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.conteneur_frontend.rule=Host(`tasklist.morincharleseric.online`)"
      - "traefik.http.routers.conteneur_frontend.entrypoints=websecure"
      - "traefik.http.routers.conteneur_frontend.tls=true"
      - "traefik.http.routers.conteneur_frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.conteneur_frontend.loadbalancer.server.port=8080"
      - "traefik.http.routers.conteneur_frontend.middlewares=tinyauth"

networks:
  proxy:
    external: true
    driver: bridge
